### ISSUE TITLE
Multiple hook targets for a DecoratorController

### ISSUE THREAD

**Issue by grantr** [GoogleCloudPlatform/metacontroller#107]
I'm considering a routing use case for Metacontroller in which a StatefulSet of routing agents wish to receive webhooks containing objects that describe the routing table. The routing agents wish to avoid coordinating amongst themselves, so they each want to receive all updates so they can build the full routing table.

This could be accomplished manually by creating an identical DecoratorController object for each replica, but then the user has to keep track of the scale of the StatefulSet and create or delete objects when that changes. It would be convenient if DecoratorController could specify a Service name and send webhooks to **all** matching endpoints.

It would be especially convenient if Metacontroller also added the list of currently known endpoints to the DecoratorController's status. Then each webhook payload would contain a list of all known endpoints, allowing routing agents to identify their place in the list (by inspecting the `Host` header) and subdivide the routing space using consistent hashing or a similar method.

**Comment by enisoc** [comment]
Let me try to put it in my own words to see if I understand:

You have a custom resource, let's call it Route. You have multiple routing agents, and each of them wants to be sent the latest value of every Route object via webhook, and get updates if anything changes.

Is that right? If so, I'm confused about where you'd want the list of known routing agents to be stored. Would it be in every Route object? Or are we only talking about one Route object?

Could this alternatively be implemented as a single DecoratorController, but the one hook that it calls fans out each request to all the agents? It seems like you could create a headless Service and implement such a hook with a Pod inside the cluster that uses in-cluster DNS to resolve the headless Service name to a list of endpoints.

**Comment by grantr** [comment]
Yep that's it.

> If so, I'm confused about where you'd want the list of known routing agents to be stored. Would it be in every Route object? Or are we only talking about one Route object?

I'm imagining there's a headless service pointing to the list of routing agent endpoints. This service is created by some other process/user, not metacontroller.

The `Route` object doesn't know anything about the routing agents. It describes a single route. The routing agents are the data plane implementation and are not represented by objects.

> Could this alternatively be implemented as a single DecoratorController, but the one hook that it calls fans out each request to all the agents?

Yes, exactly. The feature request is: I'd rather not do that myself, so can metacontroller do it instead? :)

**Comment by grantr** [comment]
I thought about this more over the weekend and realized it might make more sense as a separate webhook type `watch` in addition to `sync` and `finalize`. It doesn't make sense to allow fanned out recipients to update objects, since those updates will likely cause a resource version conflict.

**Comment by enisoc** [comment]
> Yes, exactly. The feature request is: I'd rather not do that myself, so can metacontroller do it instead? :)

If it makes sense to conceive of this as a single DecoratorController handler that does the fan-out, I feel like it's cleaner and more composable to write such a handler, rather than to make it a built-in feature of Metacontroller. I think it would be pretty trivial to implement the fan-out handler; I can try to make a quick proof-of-concept if you're not convinced.

> The Route object doesn't know anything about the routing agents. It describes a single route.

How important is it that every agent have an eventually consistent view of the routing table? If each one builds its table based on a stream of events describing individual Route objects, it seems critical that no events are missed. Missed creates and updates should be fixed eventually by a periodic resync. However, there's no guarantee of observing deletion of a Kubernetes API object unless you add a finalizer.

In this case, you'd need a finalizer that waits for acknowledgement from all agents before allowing the Route to be deleted. Is that an acceptable UX for the users or other clients that manipulate Route objects? Even then, it would be possible for an agent to miss the delete if it temporarily dropped out of the headless service for some reason.

Taking a step back, it seems like conceptually what each agent needs is to be sent the entire list of Route objects when any change occurs to any Route object. Is the key problem that there may be too many Route objects, so that this becomes wasteful of resources?

**Comment by enisoc** [comment]
The watcher sidecar sounds like a good solution for this case.

**Comment by grantr** [comment]
We'll go with that for now and see how it works out. Thanks!
