### ISSUE TITLE
Delete cascade for Job.batch/v1

### ISSUE THREAD

**Issue by mikefaraponov** [GoogleCloudPlatform/metacontroller#145]
Delete all pods related to the job after job is deleted from desired children list

**Comment by enisoc** [comment]
Hm I'm guessing this happens because the default deletion behavior for Job is non-cascading to maintain backward compatibility with clients that existed before server-side garbage collection. At first glance, I'm thinking it might make sense for Metacontroller to always request cascading deletion of children. That would fix this for Job and any other legacy objects that default to non-cascading deletion, but we should think through whether there are any exceptions to that rule.
