### ISSUE TITLE
Let the webhook choose the resync period

### ISSUE THREAD

**Issue by drigz** [GoogleCloudPlatform/metacontroller#152]
The resync period allows wrapping an external, imperative API with a CompositeController, which partially addresses the "use-case for reconciling external state" described in #93. However, because there is a single resync period for the controller, if you want to minimize the latency of the status updates, then you might set a short resync period, resulting in unnecessary polling for resources that have settled.

This could be avoided by allowing the sync hook to say when it wants to be polled again for a given resource, eg by adding a `ResyncPeriodMilliseconds` field to `SyncHookResponse`. Then the hook could say that it wants to be polled frequently for a volatile resource, but infrequently once that resource has settled.

**Comment by enisoc** [comment]
Thanks for filing this. I've already put some thought into how to do this since it also came up in discussions with @nikhilk.

I think it should be straightforward to plumb through a sync response field into a call to `queue.AddAfter()` which is [how built-in controllers get this behavior](https://sourcegraph.com/github.com/kubernetes/kubernetes@4b1282d9258e13791970a20395df4a6ec2613856/-/blob/pkg/controller/deployment/deployment_controller.go#L405).
