### ISSUE TITLE
Go client library for example controllers

### ISSUE THREAD

**Issue by hochuenw** [GoogleCloudPlatform/metacontroller#45]
Is there a way for a user to use go client to create a crd (e.g indexedJob) instead of using kubectl and yaml file?

**Comment by enisoc** [comment]
You could use the [dynamic client](https://godoc.org/github.com/kubernetes/client-go/dynamic) if you don't mind working with [Unstructured](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#Unstructured), which is essentially `map[string]interface{}`.

If you want a statically-typed Go client, you would need to write a Go `struct` that represents the IndexedJob API and then [generate a client](https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/) from it. By design, Metacontroller doesn't require controller authors to create such static types in order to write controllers, but if you choose to do so, it works the same as for any other custom resource.

**Comment by hochuenw** [comment]
@enisoc Nice comment. Thanks so much!!
