### ISSUE TITLE
How to design an operator that creates a kubernetes resource using other kubernetes resources

### ISSUE THREAD

**Issue by AmitKumarDas** [GoogleCloudPlatform/metacontroller#46]
What is the possible design I should follow for my use case detailed here:

**Scenario:**
```
When a PVC is applied, I need to check for the existence of a Custom Resource
Then I need to create a Kubernetes Service
If above Service & Custom Resource are available
Then I need to extract the cluster IP from Service & a property from Custom Resource
Then I need to create a Deployment using above cluster IP & property values
Finally, I want to create a PV using the above cluster IP
```

**Scenario:**
```
When the PVC is deleted, I want to delete Service, Deployment & PV objects
```

**Comment by enisoc** [comment]
Can you elaborate on what kind of info is in the custom resource? Is it just selecting which PVC it applies to, and giving a few properties? If so, does it select the PVC by name, by labels, or something else?

It would also help to get a summary of what you're trying to achieve. Creating PV objects for PVC makes it sound like you're trying to implement a dynamic auto-provisioner. Is that close?

For the most part, this sounds like a DecoratorController that creates a Service, Deployment, and PV and attaches them to a PVC. The twist it that it needs information from an associated custom resource that it doesn't create.

For some cases, it might make sense to forego the custom resource and put that info in an annotation on the PVC instead. If that would work for your case, DecoratorController can already do this.

If it's important that the info be in a separate custom resource (e.g. you can't control the annotations that get put on the PVC), I think this use case would depend on a new feature I've been thinking about to let controllers select objects that they don't own.

**Comment by AmitKumarDas** [comment]
Thanks @enisoc Let me try to explain by providing my workflow.

Background - I have developed an operator which is a dynamic storage provisioner. It watches for PVC & creates a PV. The provisioner code has the logic to filter its own PVC. This is already factored in by the common binding logic in `https://github.com/kubernetes-incubator/external-storage`. I am sure MetaController can reduce this binding logic as well. However, I am not bothered about this part. I would like to know how to design my workflow (_explained below_) via MetaController.

PV Creation Workflow - This PV needs to exposes a iscsi connection. In order to create an iscsi connection, the provisioner needs to create a Service & then extract its `spec.clusterIP` for later usage. The next step for provisioner is to get the `spec.path` value from a Custom Resource. Below is the sample CR:

```yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: ssd
  type: hostdir
spec:
  path: "/var/myebs"
```

Above extracted values i.e. IP & path are set as `spec.containers[0].args` & `spec.volumes[0].hostPath` in a Deployment yaml before applying this Deployment. This Deployment runs a storage filesystem. Finally, the Service's `spec.clusterIP` is exposed as the `spec.iscsi.targetPortal` in the PV as shown below:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.16.154.81
```

On the whole, in order to create a PV, I need to create multiple Kubernetes resources (e.g. Service, Deployment(s)). However, these resources require some of their properties' value determined at run-time based on other resources (e.g. Service that was just created & CR that would have been created earlier).

**Comment by enisoc** [comment]
Thanks for the details. It took me a while to get back to this after finishing the [Metacontroller user docs](https://metacontroller.app), but I'll go ahead and reply in case you or someone else still find it useful.

Since you said the PVC binding logic is taken care of elsewhere, I think it should be possible to implement just the "PV creation" workflow with Metacontroller.

1. The first thing I would suggest is to create a CRD that represents this whole workflow, something like `kind: OpenEBSVolume`.
1. The controller that filters PVCs and maps the `storageClassName` to a StorageClass should then create an OpenEBSVolume instead of directly creating a PersistentVolume. Based on the `storage-pool` parameter in the StorageClass, this controller (the one that doesn't use Metacontroller) should fetch the corresponding StoragePool object and pull out the necessary data from it (e.g. `spec.path`). It should inject this data into the OpenEBSVolume object, which makes sure it's available to the "PV creation" workflow.
1. Once the OpenEBSVolume is created, it gets processed by the "PV creation" workflow controller, which is the part you can write with Metacontroller.
1. Upon receiving a given OpenEBSVolume object, your CompositeController hook would execute the following logic:
   1. Generate a Service and add it to the desired `children` list (to be passed back as JSON at the end of the hook).
   1. Check the hook input `children` list (already-existing objects) to see if there is already a Service, and if so, check if it has a `spec.clusterIP` value filled in. If the field is empty or missing, return the list of children generated so far (there's nothing more to do until that's set).
   1. If `spec.clusterIP` is filled in, generate a Deployment while filling in the clusterIP where it needs to go and also copying over the `path` that was given in the OpenEBSVolume's `spec`. Add it to the list of children to return. At this point, you can also create the PersistentVolume object and report that the PV was created in the OpenEBSVolume `status` field.

In general, the pattern is to conditionally generate things only if the things they depend on are ready. In this case, you don't generate the Deployment until you see that the `spec.clusterIP` has been materialized in the observed Service. Metacontroller will take care of calling your hook again if anything changes, so you just need to check if the condition you're waiting for is satisfied or not on each invocation.
