### ISSUE TITLE
Execute custom cleanup code on deletion with finalizers

### ISSUE THREAD

**Issue by gurvindersingh** [GoogleCloudPlatform/metacontroller#60]
The use case is what I have discussed with you @enisoc in #58. We (@folago and me) are trying to implement a LB controller based on `Service` resource using `DecoratorController`. We create an external LB when a new service is created and pass the info using annotations on the `Service` resource. But when the `Service` resource gets deleted, we need to have this info passed to our controller, so we can delete the LB entry for this service as well. As the [code](https://github.com/GoogleCloudPlatform/metacontroller/blob/master/controller/decorator/controller.go#L249) stands now, it is only possible to delete the objects in the cluster using ownerreference, but objects created outside the cluster is not possible to clean up. It would be good to have this as a configurable option in the controller spec and default disabled, if preferred, to preserve the current behavior.

**Comment by enisoc** [comment]
I think we can support this use case with [finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#finalizers). Without a finalizer, we would have to rely on seeing the one-time "delete" watch event, which is an anti-pattern in level-triggered control logic.

With a finalizer, we can guarantee that the object won't disappear until you've cleaned up the external state. It might work something like this:

1. We add a `finalize` hook to the Metacontroller APIs in addition to the `sync` hook. You can implement this as a separate webhook, or just set the same webhook URL as `sync` if you want to handle everything in one hook.
2. If you define a `finalize` hook, we'll add a finalizer to the parent object for you before calling your `sync` hook for the first time. That way, we know the finalizer exists before you ever allocate anything external that will need to be cleaned up.
3. When the parent gets deleted, the finalizer will cause it to enter a "pending deletion" state instead of disappearing immediately. While it's pending deletion, we'll call your `finalize` hook instead of `sync` whenever something changes. This is your chance to clean up external state, as well as decide if you want to delete some children in a particular order (another use case I've been wanting to support for graceful shutdown of complex apps).
4. We will not remove the finalizer, allowing the parent to exit the "pending deletion" state and disappear, until your `finalize` hook returns a result that tells us you are ready.

@gurvindersingh Can you comment on whether this would work for your use case?

cc @janetkuo @liyinan926 @crimsonfaith91 for comments on the proposed API change.

**Comment by gurvindersingh** [comment]
@enisoc `finalize` hook will work as you proposed for our use case. Also having a possibility to call a separate endpoint for `finalize` hook is preferable as it would help to modulerize the code.

**Comment by crimsonfaith91** [comment]
I lean towards having a separate webhook for the `finalize` hook. Does `finalize` hook indirectly support cross-namespace cleanup?

**Comment by gurvindersingh** [comment]
@enisoc any update on this, thanks !!

**Comment by enisoc** [comment]
@gurvindersingh I hadn't yet ranked this feature request among the other work we have planned. If you would start using this feature and giving feedback on it very soon, I am inclined to prioritize this higher. Please let me know if this is blocking something you want to work on right now, or if you were just curious whether we've started on this (we haven't yet).

**Comment by gurvindersingh** [comment]
@enisoc we definitely plan to use this feature. Only question about feedback is that we can provide it either in August or September. SO hopefully this provide you enough information to prioritize this feature accordingly.

**Comment by mgoodness** [comment]
I would use this functionality as well - and soon. My thought/plan is to use metacontroller to trigger a webhook that would (among other things) create an entry in an external DB when a Namespace is created/updated, and delete the entry on deletion.

**Comment by folago** [comment]
Any update on this? We are ready to test this feature as it comes out.

**Comment by enisoc** [comment]
@folago I just got back from a leave of absence and I'm still catching up on reviews, but this is probably going to be the next thing I work on when I get back to coding, unless someone else gets to it first.

**Comment by rlguarino** [comment]
@enisoc looks like you're working on this now can I help somehow? This was going to be the next thing on my todo list.

**Comment by enisoc** [comment]
I've started implementing the easy parts, which are adding the API field, calling the new hook, and adding/removing the finalizer.

One thing I've realized might become a blocker is what to do if the user turns on a finalizer hook, we add the finalizer to a bunch of objects, and then the user turns off the finalizer or deletes the controller entirely. If we do nothing, the user will end up with a bunch of undeleteable objects, which is not very nice.

I'm wondering if we should make an effort to process (and remove) any finalizer added by Metacontroller (they'll all have a known prefix), on any object pending deletion, if we know that there is no lambda controller defined which would handle that finalizer. We'd need to be careful to tie this to the lifecycle of the lambda controller's definition (e.g. the CompositeController object), rather than to that of the actual control loop (e.g. the parentController instance), because we restart the control loop whenever the definition changes. We don't want to erroneously process finalizers during that brief downtime of the control loop.

Given that, I'm thinking this would make sense as its own global control loop within Metacontroller. The hard part is knowing which types of objects it needs to watch and/or scan for finalizers. Ideally we could have it list/watch "objects of any resource at all that are in a pending-deletion state", but I don't know of an efficient way to do that without putting a lot of load on the API server.

If you're still interested in helping with finalizers, you could put some thought into this harder problem while I finish up the easy parts. :)
