### ISSUE TITLE
Can’t label on node with DecoratorController

### ISSUE THREAD

**Issue by sngchlko** [GoogleCloudPlatform/metacontroller#61]
When i use DecoratorController for labeling node, nothing happend.
```
$ kubectl logs metacontroller-57dfc8cffc-jcx2t
round_trippers.go] GET https://172.30.0.1:443/apis/v1 200 OK in 1 milliseconds
controller.go:391] Node /10.0.0.1 has been deleted
controller.go:391] Node /10.0.0.2 has been deleted
controller.go:391] Node /10.0.0.3 has been deleted
```
DecoratorContoller can’t find parent object such as node
because the node doesn’t have a namespace.

**Comment by rlguarino** [comment]
I just ran into the same thing with a Cluster scoped CRD.

**Comment by enisoc** [comment]
In general, Metacontroller doesn't yet support cluster-scoped objects like Node, for reasons discussed in #2.

For DecoratorController in particular, I don't think attachments would work for a cluster-scoped resource. I guess labels and annotations could work with the fix you proposed, but it would be confusing if some features of the API work and others don't. On the other hand, it seems a shame to prevent the things that could work just because not everything works.

I'll take a look at #62 and think about ways to clarify what does and doesn't work for cluster-scoped resources. Or maybe we should double down on finding a general solution for #2 that lets all Metacontroller APIs work for cluster-scoped resources.
